export const FETCH_PRODUCTS = 'FETCH_PRODUCTS';
export const APPLY_FILTER = 'APPLY_FILTER';
export const ADD_TO_CART = 'ADD_TO_CART';
export const REMOVE_FROM_CART = 'REMOVE_FROM_CART';
export const EMPTY_CART = 'EMPTY_CART';
export const ADD_ORDER = 'ADD_ORDER';
export const SELECT_PRODUCT_ITEM='SELECT_PRODUCT_ITEM';
export const SWITCH_PRODUCT_BG_IMAGE='SWITCH_PRODUCT_BG_IMAGE';
